trigger:
  branches:
    include:
      - main
      - develop
      - rc/*
      - patch/*

pr:
  branches:
    include:
      - main
      - develop
      - rc/*
      - patch/*

variables:
  containerRegistry: 'uchimera'
  buildId: '$(Build.BuildId)'
  branch: '$(Build.SourceBranchName)'
  isDevelop: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
  repoName: 'howler-ui'
  isPrBranch: $[eq(variables['Build.SourceBranchName'], 'merge')]

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: BuildAndTestSource
        displayName: Build And Test Source
        steps:
          - script: |
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
              nvm install lts/gallium
              npm install -g yarn
              echo isPrBranch: $(isPrBranch)
              yarn install
              export REACT_APP_BRANCH=$(branch)
              export REACT_APP_COMMIT_HASH=$(Build.SourceVersion)
              yarn run build
              # yarn test -- --coverage
            displayName: 'npm install, build and test'
