trigger:
  branches:
    include:
      - main
      - develop
      - rc/*
      - patch/*

pr:
  branches:
    include:
      - main
      - develop
      - rc/*
      - patch/*

variables:
  containerRegistry: 'uchimera'
  buildId: '$(Build.BuildId)'
  branch: '$(Build.SourceBranchName)'
  isDevelop: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]
  repoName: 'howler-ui'
  isPrBranch: $[eq(variables['Build.SourceBranchName'], 'merge')]

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: BuildAndTestSource
        displayName: Build And Test Source
        steps:
          - script: |
              echo isPrBranch: $(isPrBranch)
              yarn install
              export VITE_BRANCH=$(branch)
              export VITE_COMMIT_HASH=$(Build.SourceVersion)
              yarn run build
            displayName: 'Vite build'
